platform :ios, '10.0'
use_frameworks!
inhibit_all_warnings!
source 'https://github.com/CocoaPods/Specs.git'
target 'BaseIOS' do
  # Core
  pod 'YYKit'
  pod 'ReactiveObjC'
  pod 'Masonry'
  pod 'SDAutoLayout'
#  pod 'AsyncDisplayKit'
  pod 'YTKNetwork'
  pod 'FMDB'

  # UI_Component
  pod 'MJRefresh'
  pod 'IQKeyboardManager'
  pod 'SVProgressHUD'
  pod 'IQKeyboardManager'
  pod 'XHLaunchAd'
#  pod 'SGPagingView'
#  pod 'JXCategoryView'
#  pod 'JXPagingView/Pager'
#  pod 'AXWebViewController'
#  pod 'WMZBanner'
#  pod 'TXScrollLabelView', '1.3.2'
#  pod 'MSNumberScrollAnimatedView'
#  pod 'XRWaterfallLayout'
#  pod 'XHInputView'
#  pod 'IDMPhotoBrowser'
#  pod 'TZImagePickerController'
#  pod 'ActionSheetPicker-3.0'
#  pod 'CRBoxInputView'

  # Third_Platform
  pod 'JPush'
  pod 'RongCloudIM'
  pod 'RongCloudRTC/RongCallLib'
  pod 'UMCCommon'
  pod 'UMCCommonLog'
  pod 'UMCAnalytics'
  pod 'UMengUShare/UI'
  pod 'UMengUShare/Social/ReducedWeChat'
  pod 'UMengUShare/Social/ReducedQQ'
  pod 'UMengUShare/Social/ReducedSina‘
end
