# NYSExampleObjC
# https://github.com/niyongsheng/NYSKit

platform :ios, '13.0'
inhibit_all_warnings!
source 'https://github.com/CocoaPods/Specs.git'

target 'NYSExampleObjC' do
  use_frameworks!
  pod 'NYSKit', :path => "../../"
  pod 'NYSUIKit', :path => "../../"
  pod 'CocoaDebug', :configurations => ['Debug']

  # Core
  pod 'FMDB'
  pod 'YYKit'
  pod 'Masonry'
  pod 'XHLaunchAd'
  pod 'ReactiveObjC'
  pod 'IQKeyboardManager'
  pod 'IQKeyboardManager'
  pod 'NYSTK','~>0.0.5'

  # Third
  pod 'JPush'
  pod 'UMCCommon'
  pod 'UMCCommonLog'
  pod 'UMengUShare/UI'
  pod 'UMengUShare/Social/ReducedWeChat'
  pod 'UMengUShare/Social/ReducedQQ'
  pod 'UMengUShare/Social/ReducedSina‘
  
  post_install do |installer|
    installer.generated_projects.each do |project|
      project.targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
        end
      end
    end
  end
  
end
